server:
  port: 8081

spring:
  application:
    name: USER-SERVICE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
    instances:
      usersPostsGetService:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 100
        permitted-number-of-calls-in-half-open-state: 5
        max-wait-duration-in-half-open-state: 10s
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-size: 5
        sliding-window-type: count_based
        register-health-indicator: true
